name: 'ga4_bq_dbt_portfolio'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  ga4_start_date: '20210101'
  ga4_end_date: '20210131'

models:
  ga4_bq_dbt_portfolio:  
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table